Premiere version du client
digitick/infoconcert-client pull request #1
Opened 2016-12-06 13:36 UTC by hadeli

# Fonctionnalités
* Connexion en HMAC
* Récupération des listes d'artistes
* Récupération des infos d'un artiste donnée

2016-12-06 15:27 UTC, nmariani requested changes

2016-12-06 15:27 UTC, nmariani commented on composer.json
> +    "name": "digitick/infoconcert-api-client",
digitick/infoconcert-client

2016-12-06 15:27 UTC, nmariani commented on README.md
> +## Codes d'erreurs
Ajouter Définition codes Domaine/Sous-domaines

2016-12-06 15:27 UTC, nmariani commented on src/Digitick/Infoconcert/Model/ArtistList.php
> +                continue;
throw exception fields mismatch

2016-12-06 15:27 UTC, nmariani commented on src/Digitick/Infoconcert/Model/ArtistList.php
> +                $countRequiredFields > count($rowKeys) ||
drop

2016-12-06 15:27 UTC, nmariani commented on src/Digitick/Infoconcert/InfoconcertClient.php
> +<?php
Split ArtistClient / HttpCLient (composition)

2016-12-06 15:27 UTC, nmariani commented on src/Digitick/Infoconcert/Model/ArtistListItemInterface.php
> +use DateTime;
root namespace \ c'est bien aussi ^^

2016-12-06 15:27 UTC, nmariani commented on src/Digitick/Infoconcert/Model/Artist.php
> +use InvalidArgumentException;
root namespace \ c'est bien aussi ^

2016-12-06 15:27 UTC, nmariani commented on src/Digitick/Infoconcert/InfoconcertClient.php
> +use ErrorException;
root namespace \ c'est bien aussi ^^

2016-12-06 15:27 UTC, nmariani commented on src/Digitick/Infoconcert/InfoconcertClient.php
> +use InvalidArgumentException;
root namespace \ c'est bien aussi ^^

2017-01-10 15:27 UTC, atogeek commented
Hello,
Je suis entrain d'implémenter un client pour l'API Info concert mais j'ai un soucis avec la route list/events --> le paramètre [country] ne semble pas être pris en compte.. ce qui est pas mal gênant.

Je vois que vous ne l'avez pas implémenter sur ce client.. vous avez des idées ?

Merci!

2019-02-25 08:37 UTC, closed without merging